//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaFiguras.Cliente.AFigurasServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AFigurasServiceReference.AreaFigurasWebServiceSoap")]
    public interface AreaFigurasWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        int AreaCuadrado(int lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AreaCuadradoAsync(int lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        double AreaTriangulo(int @base, int altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AreaTrianguloAsync(int @base, int altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        double AreaCirculo(double radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AreaCirculoAsync(double radio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreaFigurasWebServiceSoapChannel : AreaFiguras.Cliente.AFigurasServiceReference.AreaFigurasWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreaFigurasWebServiceSoapClient : System.ServiceModel.ClientBase<AreaFiguras.Cliente.AFigurasServiceReference.AreaFigurasWebServiceSoap>, AreaFiguras.Cliente.AFigurasServiceReference.AreaFigurasWebServiceSoap {
        
        public AreaFigurasWebServiceSoapClient() {
        }
        
        public AreaFigurasWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreaFigurasWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaFigurasWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaFigurasWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AreaCuadrado(int lado) {
            return base.Channel.AreaCuadrado(lado);
        }
        
        public System.Threading.Tasks.Task<int> AreaCuadradoAsync(int lado) {
            return base.Channel.AreaCuadradoAsync(lado);
        }
        
        public double AreaTriangulo(int @base, int altura) {
            return base.Channel.AreaTriangulo(@base, altura);
        }
        
        public System.Threading.Tasks.Task<double> AreaTrianguloAsync(int @base, int altura) {
            return base.Channel.AreaTrianguloAsync(@base, altura);
        }
        
        public double AreaCirculo(double radio) {
            return base.Channel.AreaCirculo(radio);
        }
        
        public System.Threading.Tasks.Task<double> AreaCirculoAsync(double radio) {
            return base.Channel.AreaCirculoAsync(radio);
        }
    }
}
